version: "{branch}-ci-{build}"
image: Visual Studio 2017

build: msvc
platform: x86
configuration: Debug

install:
- choco install opencppcoverage codecov
- set PATH=C:\Program Files\OpenCppCoverage;%PATH%

build_script:
- mkdir build && cd build
- cmake ..
- MSBuild Example.sln /p:Configuration=%configuration% /p:Platform="Win32" /nologo /m /verbosity:minimal
- OpenCppCoverage --export_type cobertura:coverage.xml --modules "*.exe" --cover_children -- ctest -C %configuration% --output-on-failure
- codecov -f coverage.xml --root %APPVEYOR_BUILD_FOLDER%
